### ISSUE TITLE
Add Members a Group

### ISSUE THREAD

**Issue by cpaybr** [SkidGod4444/TeleGram-Member-Adder#1]
Good morning! First congratulations, your code was excellent.
I'm just having a problem, to add members to the group, the listing only appears for the groups that I entered, the groups that I create do not appear. Can you help me?

Thanks

**Comment by SkidGod4444** [comment]
Hey, it's me SkidGod4444
As you are suffering from a error i will recommend you to watch our YouTube
video properly of this respective code: https://youtu.be/0_ujOQi0WVA
If still it's not helpful then try to use a different phone number and the
group should be made before you login the telegram.org.me website.
Else for more help join our discord server: https://discord.gg/floater

**Comment by ealcober** [comment]
Hi, following instructions members.csv file is totally empty. Does the user must be the owner of the group or something missed?

**Comment by SkidGod4444** [comment]
Kindly follow the steps from : https://youtu.be/0_ujOQi0WVA

**Comment by ealcober** [comment]
Empty file following instructions… this scripts works with only public
groups? Do the API owner must be the owner of the groups? Please explain
that relation or give some referrence

**Comment by SkidGod4444** [comment]
If you are trying to add memebers in a grp then you must be the owner of
that grp i mean the I'd u are using that I'd must have the ownership.
